list: $/nocio/formstore/models/form/columns.yaml
modelClass: Nocio\FormStore\Models\Form
title: Forms
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
recordsPerPage: '8'
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nocio/formstore/forms/update/:id'
