list: $/nocio/formstore/models/submitter/columns.yaml
modelClass: Nocio\FormStore\Models\Submitter
title: Submitters
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: '8'
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nocio/formstore/submitters/update/:id'
