# ===================================
#  Relation Behavior Config
# ===================================

data:
    label: Data
    view:
        form: $/nocio/formstore/models/datasuednord/fields.yaml
