list: $/nocio/formstore/models/submission/columns.yaml
modelClass: nocio\FormStore\Models\Submission
title: Submissions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'nocio/formstore/submissions/update/:id'
